server:
  port: 10086
  compression:
    enabled: true
    mime-types: text/css,text/javascript,application/javascript,application/json,image/jpeg,image/png,image/gif
    min-response-size: 2KB

spring:
  application:
    name: clp

  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true
        cache-public: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trymongodb
